# Generated by Django 3.2.16 on 2023-01-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='Rates',
        ),
    ]
